#!/bin/bash
FILE=$VIRTUALENVWRAPPER_HOOK_DIR/fbbotw/bin/postactivate

LINE='export PAGE_ACCESS_TOKEN=EAAYiKvTIihQBAGp5T9M8EDE4wWuu01v39bEjw2i82atSHUTzCcqqnQMsEJrLsZAbU9ZBIQZAkO9RZCmaesalGBtcjX8tuFq8z2SYiT6VxdH1IWf2l17kegoQ0ZAttMnsQZAMMZBUPp3OtCOvQWKGuVzKrFEv1qdsQXsYYBHgFqaHAZDZD'
grep -q -F "$LINE" "$FILE" || echo $LINE >> $FILE

LINE='export FBID=1198658993509311'
grep -q -F "$LINE" "$FILE" || echo $LINE >> $FILE

#unset DJANGO_SETTINGS_MODULE
